### PR TITLE
Updated to Create 0.5.1

### PR DESCRIPTION
**Pull request by AdalynBlack**
I decided to go through and update the dependencies and code for the mod to work with Create 0.5.1.b and above. I did a bit of testing and didn't find any immediately obvious issues or errors, which makes sense, as most changes were just semantic. I didn't do any major changes to any of the code, but major changes will be needed for future updates, as the addLayer function for Registrate is now deprecated

### CODE REVIEW

**Comment by Lgmrszd** [comment]
Thanks for the effort, unfortunately I already made an updated version, just for 1.18.2 branch
I should've done the same for 1.19.2 but I got too much other stuff to deal with 😭
If you want, you can make another PR, by merging/rebasing 1.18.2 updated branch on top of current 1.19.2 branch

**Comment by johalun** [comment]
Thanks for the effort @TonyGamer and @Lgmrszd ! I would love to see this on 1.19.2 soon. It's currently the only create addon mod to get compatibility with 5.1 in the pack I'm playing. (sorry for the pressure ;) )

**Comment by AdalynBlack** [comment]
> Thanks for the effort, unfortunately I already made an updated version, just for 1.18.2 branch I should've done the same for 1.19.2 but I got too much other stuff to deal with 😭 If you want, you can make another PR, by merging/rebasing 1.18.2 updated branch on top of current 1.19.2 branch

I'll look into doing that. Shoulda checked a bit further before updating it all lol

**Comment by Lgmrszd** [comment]
Gotta close it as new version is out already... But in any case, thanks for your effort, goes to show how important this mod is for some people 🙂

**Pull request closed without merging**
