### PR TITLE
Compatibility with Create 0.5d

### PR DESCRIPTION
**Pull request by wchen1990**
- Create no longer shadows Registrate, so this project needs to either
  shadow it itself or use the same Jar-in-Jar method Create does for
  Registrate
- Builds and runs fine outside of dev, but runClient no longer works

### CODE REVIEW

**Comment by Lgmrszd** [comment]
Funny that I actually also use and then Shadow Registrate, but at some point I probably switched to Create's repacked one by accident, oops.
Is there a reason why CurseMaven is used for Create and Flywheel instead of terrag repo?

**Comment by wchen1990** [comment]
Yea, was using the curse maven files because Create 0.5d changed artifact paths and using that I was unable to get it mapped for some reason. Didn't really spend too much time trying to figure that out since I wanted to see what the compatibility issues were.

**Comment by Lgmrszd** [comment]
Made #12 to track the progress.
Most likely I won't add this PR as I'm trying to work around to make runClient work but if you find a way to fix that it would be greatly appreciated!

**Comment by Lgmrszd** [comment]
Found a solution which fixes run tasks, but thanks anyway!

**Pull request closed without merging**
