### PR TITLE
Create es_es.json

### PR DESCRIPTION
**Pull request by albertosaurio65**

### CODE REVIEW

**Comment by Lgmrszd** [comment]
Hello, thanks for the localization! I've updated dev branch, could you check latest en localization file in here?
(https://github.com/Lgmrszd/CompressedCreativity/blob/1.18_dev/src/generated/resources/assets/compressedcreativity/lang/en_us.json)

Additionally, I would appreciate if you change PR to apply to 1.18_dev branch

**Comment by albertosaurio65** [comment]
Okey, i will update de translate with the lang of the lang, and change the pr to the another branch

**Comment by albertosaurio65** [comment]
there were no changes in the lang

**Comment by Lgmrszd** [comment]
Closed in favor to #8

**Pull request closed without merging**
